- k8s/outputs/operator.cue
CI requires IfNotPresent for the operator, because we want to side-load an image. IfNotPresent avoids fetching a different one from the server. However, Always is a safer default for development work, because it's harder to accidentally run an image different from the one you just built locally.
This PR makes "Always" the default, and https://github.com/greymatter-io/operator/pull/122 tells CI to explicitly specify IfNotPresent for CI purposes.
> safer dev default pull policy

- gm/intermediates.cue
- gm/outputs/EXTRACTME.cue
- gm/outputs/catalogentries.cue
- gm/outputs/prometheus.cue
- gm/outputs/sidecar.cue
- inputs.cue
- k8s/intermediates.cue
- k8s/outputs/EXTRACTME.cue
- k8s/outputs/dashboard.cue
- k8s/outputs/prometheus.cue
[sc-10539]
Adds prometheus to k8s.  Creating prometheus, its mesh configs, updating catalog entries and dashboard configs can be toggled by changing `defaults.enable_metrics` in the input.cue.
> Add Prometheus k8s and mesh configs

- gm/intermediates.cue
- inputs.cue
Make sure that the CUE evaluates with the correct values. When you use least_request or hash_ring load balancers ensure that their respective configuration options are included in the cluster (they are set to default values).
You can do all testing on the kops cluster I created and populated. There are 4 deployed services, each with a different type of load balancing (all the ones we support).
`awsume bs-resources-admin`
`kops export kubeconfig jack.k8s.local --admin`
`k get pods -A` to verify
In a terminal window, attach to an apple pod's logs:
`kubectl logs -n produce-aisle apple-755654bd79-85nl6 -c sidecar -f`
in a separate window:
`curl -vL a2148c3dcdd7240ca99350a3f49b73d3-557938267.us-east-1.elb.amazonaws.com:10808/services/apple`
Run it a few times, and make sure each pod gets …
> Add load balancer configurations

- gm/intermediates.cue
[sc-18171] 
Use `gm_oidc-validation` to get the users's name from the access_token JWT claim. The header containing the name value must be set to USER_DN (for now) because gm-proxy was initially written to support PKI. This change influences the behavior of `gm.observables`, where the USER_DN value is set to the `originatorToken` in the observable log event. The originatorToken is a queryable field that the Observables App uses to aggregate user activity.
> get user name from jwt claim using userinfo

- gm/outputs/edge.cue
I like having the toggle right in the edge.cue file because it's simpler to change the boolean than copy/pasting the k/v pair. I also updated the OPA section of the playbook to reflect this.
> add ext_authz toggle to edge.cue

- k8s/outputs/operator.cue
The operator needs to know our Bugsnag API token to report to the service. Hoisting that value into the code through environment variables requires a change to its k8s manifests to connect an environment variable to a k8s secret. This PR includes a env block that maps a statically defined secret name containing a bugsnag api token to an environment variable that the dev build of the operator expects to exist. Because the env var is set to optional (and the non-dev build does not contain any bugsnag code) a user (specifically non-internal end user) never needs to set it. 
Please evaluate the CUE to ensure it is valid
> Add Bugsnag environment variable populated by secret

- inputs.cue
- k8s/outputs/operator.cue
This is a companion pr to (https://github.com/greymatter-io/operator/pull/148) change to the operator which adds a config.  
`auto_copy_image_pull_secret` settings:
- `true` will have the standard feature which will copy the image pull secret from the gm-operator namespace into the install namespace as well as any watch namespaces
- `false` will not copy the image pull secret.  The operator does log if it can not find the secret.
> The operator will still create all resources required for greymatter core however these will fail to start until an image pull of name `gm-docker-secret` is added to the namespace.
Refer to companion pr for testing instructions.
> update operator cue and input cue for new operator config

- k8s/outputs/EXTRACTME.cue
…us for us.
This will provide an up to date clean way for us to provide someone managing an external prometheus the info they need to set it up to scrape greymatter.
EX:
To get a base set of rules prometheus needs to scrape greymatter run `cue eval -c ./k8s/outputs -e prometheus_scrape_rules_yaml --out text > prometheus-rules.yaml` this will result in a config map where you can see the rules we apply to our prometheus instances.
To see a list of kuberenetes RBAC permissions we set run `cue eval -c ./k8s/outputs -e prometheus_rbac_yaml --out text > prometheus-rbac.yaml`
> Clean export prometheus rules

- k8s/outputs/operator.cue
Now that the debug container will become the default development container, it needs to match the behaviors and functionalities of the normal build. 
To test, look at the jack.k8s.local kops cluster. Describe the operator pod, look that the debug image is running and the cmd args contain the values listed in the PR. Confirm that the operator is running successfully.
> Match operator debug command arguments with release command arguments

- k8s/intermediates.cue
- k8s/outputs/catalog.cue
- k8s/outputs/controlensemble.cue
- k8s/outputs/dashboard.cue
- k8s/outputs/edge.cue
- k8s/outputs/prometheus.cue
- k8s/outputs/redis.cue
- k8s/outputs/spire.cue
[sc-20865]
This PR adds resource blocks to all deployments and stateful sets.
Setup your operator.yaml file to point to this branch and `kubectl apply -f operator.yaml` when the pods are stood up you should be able to see the dashboard.
Looking at the yaml for each pod you will see a resource block for all containers in each pod.
> add resource blocks to all deployments and stateful sets

- k8s/outputs/controlensemble.cue
- k8s/outputs/dashboard.cue
- k8s/outputs/edge.cue
- k8s/outputs/prometheus.cue
- k8s/outputs/spire.cue
A recent addition of resource definitions assumed much larger resource pools than necessary. For example, the mesh could start in our integration test clusters before the change, but could not after the change. This PR reduces the resources until spire and the mesh could start up again. 
This operator pr uses this branch:
https://github.com/greymatter-io/operator/pull/147/files/793b8751b876bd4293cad2dc21270e82af7b4c4c..bc743e0f3f9a143c78ff9ae562f3daa387783ef0
go to the recently built pipeline:
https://buildkite.com/greymatter/operator/builds/991
Notice how the spire tests fails after verifying the pods are alive (this is a known issue with spire not receiving ids. if it was resource related, the script would timeout waiting for the pods to start)
> Resource reduction

- gm/intermediates.cue
- gm/outputs/EXTRACTME.cue
- gm/outputs/jwtsecurity.cue
- inputs.cue
- k8s/intermediates.cue
- k8s/outputs/EXTRACTME.cue
- k8s/outputs/jwtsecurity.cue
[sc-20732]
[sc-24282]
This is a two-pronged review because the commits include code to verify the filter is working. After a reviewer confirms the filter works as intended, then I'll have to remove that code. The testing code is found in the edge.cue file. 
The gist of this PR is to add a toggle to deploy the jwtsecurity service with some configuration set in the inputs.cue (so users dont need to delve into the k8s cue), and to add a toggle to enable the http filter. There is also a "helper object" to easily connect the sidecar proxy with the enabled filter to jwtsecurity. This is a similar pattern to what I did with ext_authz and OPA. 
To test:
I have a kops cluster running an operator pulling configurations from this branch. The edge proxy has the filter enabled. To connect to it:
``` …
```
> Add JWTSecurity Filter and Service Toggle

- k8s/outputs/operator.cue
The README instructs users to create a secret containing their private key with a filename of ssh_private_key instead of id_ed25519. By default, the generated manifests should match.
> Correct private key path

- CHANGELOG.md
- gm/intermediates.cue
- gm/outputs/edge.cue
- inputs.cue
- k8s/outputs/dashboard.cue
This allows the intermediate definition to track the actual generated definitions from the proxy. In particular, this allows the user to access the authRealms and authAdminRealms fields necessary for keycloak backwards compatibility. The user can toggle between pre-v17 and v17+ configurations by using the keycloak_pre_17 field in the inputs defaults.edge.oidc struct. 
**Syntax Testing** 
1. Evaluate the CUE. Ensure that the two new fields have the default values (do not contain "auth")
2. Turn on keycloak_pre_17 in inputs.cue. Evaluate the CUE and confirm that the new fields do contain "auth". Ensure the provider field also contains "auth" in the url path.
**Functional Testing**
I created a kops cluster, jack.k8s.local, with an operator configured to pull changes from the …
> Add new oidc configuration options and legacy keycloak toggle

- gm/intermediates.cue
- gm/outputs/EXTRACTME.cue
- gm/outputs/catalog.cue
- gm/outputs/controlensemble.cue
- gm/outputs/dashboard.cue
- gm/outputs/edge.cue
- gm/outputs/jwtsecurity.cue
- gm/outputs/observables.cue
- gm/outputs/prometheus.cue
- gm/outputs/redis.cue
- gm/outputs/sidecar.cue
- inputs.cue
- k8s/intermediates.cue
- k8s/outputs/edge.cue
Enable mtls for internal mesh components requires tls to be enabled on the edge node.  See docs PR https://github.com/greymatter-io/gm-docs/pull/125.
The default behavior is to re-use the edge ingress secret's data however you can set up a different cert for external tls and internal mTls.
Fundamentally the logic in the domain and cluster functions in intermediate.cue rely on the naming convention of `_local` which allows the function to determine which mesh objects require ssl blocks.  Using this limits the additional fields required in service.cue calls to the functions. 
[sc-20740]
> Enable mtls connections for all internal core components

- inputs.cue
We can roll this into trunk now, and change it to a release when the overall 1.8 release is out.
> Update gm-jwt-security to 1.3.2-rc.1

- gm/outputs/EXTRACTME.cue
- gm/outputs/observables.cue
- inputs.cue
- k8s/outputs/EXTRACTME.cue
- k8s/outputs/jwtsecurity.cue
[sc-28115]
Follow the pattern with the `jwtsecurity`  top-level toggle but for the image name instead. The goal here is that no one should know that jwtsecurity is a thing if they don't dig for it. 
To test,
1. Evaluate the project as is. It should work.
2. In inputs.cue defaults, add `jwtsecurity: true`. Eval both k8s and gm, confirm that the jwt manifests appear and the jwt configs appear.
3.  add to defaults `jwtsecurity_image: "RANDOMNAME"`. Ensure that the k8s manifests contain the new image name. 
4. Set jwtsecurity to false. Ensure both k8s and gm no longer contain jwt.
> Make existence of jwt_security image optional

- .buildkite/pipeline.yaml
- .buildkite/scheduled-build.yaml
- CHANGELOG.md
- gm/outputs/dashboard.cue
- inputs.cue
- scripts/bootstrap
- scripts/cibuild
- scripts/test
- scripts/update
This is the first of a few PRs today that transition this repo from gitops-core to greymatter-core. The existing greymatter-core repo will be deleted and this repo renamed. Since most of this comes from two already reviewed/approved PRs from greymatter-core, I don't think too much time needs to be spent re-reviewing.
This PR contains the following changes:
- CI configs https://github.com/greymatter-io/greymatter-core/pull/1 (Coleman previously approved)
- Dashboard route CUE guidance https://github.com/greymatter-io/greymatter-core/pull/4 (Kyle previously approved)
- Minor clean up to inputs.cue
> add ci configs for release

- gm/intermediates.cue
Our default circuit breaker configs now matches [Envoy's defaults](https://www.envoyproxy.io/docs/envoy/v1.16.5/api-v3/config/cluster/v3/circuit_breaker.proto.html#config-cluster-v3-circuitbreakers-thresholds). I removed max_connection_pools because, if undefined, Envoy will set this to unlimited, thus I removed it. We can document it existence in gm-docs and explain when to use it.
> match envoy circuit breaker defaults

- gm/intermediates.cue
During my testing of PKI + RBAC I came across the lack of a configuration in the domain ssl_config for require client certs on the TLS handshake.
> add domain toggle for require_client_certs

- inputs.cue
In our haste to cut component releases we didn't update images in inputs.cue. These versions coincide with https://github.com/greymatter-io/infra-automation/blob/main/release-bundle/release.toml. Once merged, we'll need to cut operator/greymatter-core v0.12.1.
> update images for 1.8-rc.1 release

- inputs.cue
- k8s/outputs/EXTRACTME.cue
- k8s/outputs/elasticsearch_password.cue
- k8s/outputs/observables.cue
- k8s/outputs/vector.cue
This PR adds a Secret containing a fake password for Elasticsearch. This allows the audit app/pipeline pods to start at install-time of the mesh. The other necessary change was to provide a non-empty string for the Elasticsearch host. Without this the audit pipeline wouldn't start. These changes ensure that all pods start successfully when the the mesh is installed. I'll update this page https://docs.greymatter.io/getting-started/installation/#prepare-audit-pipeline to coincide with these changes. 
Run `cue eval -c ./k8s/outputs --out text -e k8s_manifests_yaml` and ensure that the K8s configs look correct. I deployed this to http://52.158.165.57:10808 and confirmed the changes worked.
> add elasticsearch-password secret

- gm/outputs/observables.cue
- inputs.cue
I've reverted the addition that checks for mounted_certs boolean. We always want to connect to Elasticsearch using TLS. Whether we're using one-way or two-way TLS.
> update egress cluster to elasticsearch to always use tls

- gm/outputs/observables.cue
Story details: https://app.shortcut.com/grey-matter/story/30759
This PR adds the toggle for `enable_historical_metrics` like the other core mesh services.
> fix(catalog): [sc-30759] greymatter catalog entry not displaying usage and uptime summaries

- CHANGELOG.md
- k8s/outputs/EXTRACTME.cue
[sc-29390]
to generate the manifest run: `cue eval -c ./k8s/outputs -e operator_manifests_yaml --out=text > operator.yaml`
> note: in `operator.yaml` you'll see that the gm-webhook-cert secret is now higher in the yaml than before.  It just needs to be above the operator stateful set.
> change the order of operator manifest.yaml generated by cue

- gm/intermediates.cue
- gm/outputs/EXTRACTME.cue
- gm/outputs/edge.cue
- gm/outputs/remote_jwks.cue
- inputs.cue
This PR ensures that enabling remote JWKS doesn't fail, as long as the proper values are set in inputs.cue.
Issues that were fixed:
1. The order in which mesh configs were applied. The egress to Keycloak config route would not always get created, causing a cascading effect that culminated in the edge proxy never seeing the edge-to-keycloak cluster.
2. Applying mTLS on the upstream cluster to Keycloak. The certs applied to the egress cluster did not match the upstream service's certs.
Improvements:
1. The previous implementation had users uncommenting configs in inputs.cue and edge.cue for remote JWKS. I've moved the mesh configs for egress to Keycloak to a separate CUE file that gets conditionally applied via a new boolean in inputs.cue `defaults.edge.oidc.enable_remote_jwks`. When …
> add more robust remote JWKS configs

- gm/outputs/EXTRACTME.cue
- gm/outputs/edge.cue
- gm/outputs/keycloak.cue
- gm/outputs/keycloak_postgres.cue
- gm/outputs/remote_jwks.cue
- inputs.cue
- k8s/outputs/EXTRACTME.cue
- k8s/outputs/elasticsearch_password.cue
- k8s/outputs/keycloak.cue
- k8s/outputs/keycloak_password.cue
- k8s/outputs/keycloak_postgres.cue
- k8s/outputs/keycloak_postgres_password.cue
- k8s/outputs/keycloak_realm.cue
This is a large PR, my apologies. It took me a while to get this into a basic working state. I do need someone to test this end-to-end by deploying to a k8s cluster because this is an install-time feature.  Update: Nate did this once but there have been changes since then. It'd be good for someone else to do so.
Follow the [installation docs](https://docs.greymatter.io/getting-started/installation/) but be sure to clone this `sc-29978-keycloak` branch of greymatter-core, not the latest release tag. Although, I admit, I used the old installation via git clone, not the new version since 1.8.rc2. **Be sure to set `enable_keycloak: true` and push to your repo before deploying.**
1. Once the `keycloak` pod starts, Keycloak will be accessible from a separate Kubernetes Service address from …
> Add Keycloak toggle and configs

- .buildkite/pipeline.yaml
- .buildkite/tag.yaml
- .gitignore
- inputs.cue
- scripts/cibuild
- scripts/greymatter-download-template.sh
- scripts/promotion
[sc-31811]
This PR automates a lot of the release process for us.
> This follows our new paradigm that the inputs.cue is the source of truth and not the `release.toml`
- devs can continue to work with their release-oci images in inputs.cue
- when a pr is opened to main the full main pipeline will run
-  dryrun attempt to move oci and generic artifacts to staging
- if that succeeds then it will run again and move that stuff to staging 
- generate an inputs-staging.cue w/ the staging images already changed out
- on a tag
- ask user to unblock it if there they have run a smoke test on the staging artifacts
- check to make sure the changelog has changed between the last tag and the new tag
- promote artifacts to public facing release repos
- generate a `greymatter-download*.sh` script (this …
> Automate release

- gm/intermediates.cue
[Security best practice](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies) states that we should be using secure cookies when TLS is enabled.
> conditionally set secure oidc token cookies

- inputs.cue
- k8s/outputs/observables.cue
- k8s/outputs/vector.cue
I noticed that there were a few more configs in the audit app manifest that should have been driven by toggles in inputs.cue. This will greatly reduce the need for operators to drill into the Kubernetes CUE for the app.
> add more toggles for audit app configs

- global_intermediates.cue
- gm/intermediates.cue
- gm/outputs/edge.cue
- inputs.cue
- scripts/gm_test_functions.py
Enables mtls for internal services (manual-mtls) and add tests that will ensure these stay in a good state.
[sc-32689]
Configuration Options:
| edge      | internal  | defaults.edge.enable_tls | defaults.edge.require_client_certs | defaults.core_internal_tls_certs.enable | defaults.core_internal_tls_certs.require_client_certs | configs.spire |
| --------- | --------- | ------------------------ | ---------------------------------- | --------------------------------------- | ----------------------------------------------------- | ------------- |
| plaintext | plaintext | false                    | false                              | false                                   | false                                                 | false         |
| plaintext | spire     | false …
> Enable mtls internal; add tests for it

- scripts/promotion
This PR enables the promotion script to run through without failing due to an operator image not being present in dev-oci or ci-staging-oci.
This is because of the circular dependency in greymatter core and operator.  You need to cut greymatter-core before the operator can be cut.
Those two should be in the same repo.
> Update parse and promote script to ignore the operator image

- inputs.cue
If a customer installs with `enable_audits: true` then the configurations for Elasticsearch will be used. Since Control doesn't support `localhost` this PR simply uses the local loopback IP address as a workaround. The IP address isn't supposed to do anything btw, it's just there as a starting point. The customer must still replace that value.
This PR prevents Control from going into a  nack loop due the use of `localhost` in the upstream cluster.
```
{"level":"error","service":"gm-control","stream_id":2,"cluster":"observables","locality":{"region":"default-region","zone":"default-zone"},"error":"type.googleapis.com/envoy.config.cluster.v3.Cluster:,Message \"Error adding/updating cluster(s) elasticsearch: malformed IP address: localhost. Consider setting resolver_name or setting cluster …
```
> use local loopback IP for elasticsearch_host to prevent control nack on startup
